const DU_LIEU_SAO_XAU = [
  { id: 1, ten: "Địa phá", yNghia: "Kỵ xây dựng", loai: "mapping_thang", map: ["Hợi", "Tý", "Sửu", "Dần", "Mão", "Thìn", "Tị", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất"] },
  { id: 2, ten: "Thổ phủ", yNghia: "Kỵ xây dựng, động thổ", loai: "mapping_thang", map: ["Dần", "Mão", "Thìn", "Tị", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu"] },
  { id: 3, ten: "Thổ ôn (Thiên cẩu)", yNghia: "Kỵ xây dựng, đào ao giếng, tế tự", loai: "mapping_thang", map: ["Thìn", "Tị", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão"] },
  { id: 4, ten: "Thiên ôn", yNghia: "Kỵ xây dựng", loai: "mapping_thang", map: ["Mùi", "Tuất", "Thìn", "Dần", "Ngọ", "Tý", "Dậu", "Thân", "Tị", "Hợi", "Sửu", "Mão"] },
  { id: 5, ten: "Thụ tử", yNghia: "Xấu mọi việc, trừ săn bắn", loai: "mapping_thang", map: ["Tuất", "Thìn", "Hợi", "Tị", "Tý", "Ngọ", "Sửu", "Mùi", "Dần", "Thân", "Mão", "Dậu"] },
  { id: 6, ten: "Kiếp sát", yNghia: "Kỵ xây dựng, xuất hành, giá thú, an táng", loai: "mapping_thang", map: ["Hợi", "Thân", "Tị", "Dần", "Hợi", "Thân", "Tị", "Dần", "Hợi", "Thân", "Tị", "Dần"] },
  { id: 7, ten: "Hà Khôi, Cẩu Giảo", yNghia: "Kỵ khởi công, xấu mọi việc", loai: "mapping_thang", map: ["Hợi", "Ngọ", "Sửu", "Thân", "Mão", "Tuất", "Tị", "Tý", "Mùi", "Dần", "Dậu", "Thìn"] },
  { id: 8, ten: "Vãng Vong (Thổ kỵ)", yNghia: "Kỵ động thổ, xuất hành, giá thú, cầu tài", loai: "mapping_thang", map: ["Dần", "Tị", "Thân", "Hợi", "Mão", "Ngọ", "Dậu", "Tý", "Thìn", "Mùi", "Tuất", "Sửu"] },
  { id: 9, ten: "Trùng tang", yNghia: "Kỵ khởi công, giá thú, an táng", loai: "mapping_thang", map: ["Giáp", "Ất", "Kỷ", "Bính", "Đinh", "Kỷ", "Canh", "Tân", "Kỷ", "Nhâm", "Quý", "Kỷ"] },
  { id: 10, ten: "Thiên địa chính chuyển", yNghia: "Kỵ động thổ", loai: "mapping_thang", map: ["Quý Mão", "Quý Mão", "Quý Mão", "Bính Ngọ", "Bính Ngọ", "Bính Ngọ", "Đinh Dậu", "Đinh Dậu", "Đinh Dậu", "Canh Tý", "Canh Tý", "Canh Tý"] },
  { id: 11, ten: "Thiên địa chuyển sát", yNghia: "Kỵ động thổ", loai: "mapping_thang", map: ["Ất Mão,Tân Mão", "Ất Mão,Tân Mão", "Ất Mão,Tân Mão", "Bính Ngọ,Mậu Ngọ", "Bính Ngọ,Mậu Ngọ", "Bính Ngọ,Mậu Ngọ", "Tân Dậu,Quý Dậu", "Tân Dậu,Quý Dậu", "Tân Dậu,Quý Dậu", "Nhâm Tý,Bính Tý", "Nhâm Tý,Bính Tý", "Nhâm Tý,Bính Tý"] },
  { id: 12, ten: "Thổ cẩm", yNghia: "Kỵ xây dựng, an táng", loai: "mapping_thang", map: ["Hợi", "Hợi", "Hợi", "Dần", "Dần", "Dần", "Tị", "Tị", "Tị", "Thân", "Thân", "Thân"] },
  { id: 13, ten: "Nguyệt kiến chuyển sát", yNghia: "Kỵ động thổ", loai: "mapping_thang", map: ["Mão", "Mão", "Mão", "Ngọ", "Ngọ", "Ngọ", "Dậu", "Dậu", "Dậu", "Tý", "Tý", "Tý"] },
  { id: 14, ten: "Thiên cương (Diệt môn)", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị", "Tý", "Mùi", "Dần", "Dậu", "Thìn", "Hợi", "Ngọ", "Sửu", "Thân", "Mão", "Tuất"] },
  { id: 15, ten: "Thiên tại", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Dậu", "Ngọ", "Mão", "Tý", "Dậu", "Ngọ", "Mão", "Tý", "Dậu", "Ngọ", "Mão", "Tý"] },
  { id: 16, ten: "Thiên ngục, Thiên hỏa", yNghia: "Xấu mọi việc, xấu về lợp nhà", loai: "mapping_thang", map: ["Tý", "Mão", "Ngọ", "Dậu", "Tý", "Mão", "Ngọ", "Dậu", "Tý", "Mão", "Ngọ", "Dậu"] },
  { id: 17, ten: "Tiểu hồng sa", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị", "Dậu", "Sửu", "Tị", "Dậu", "Sửu", "Tị", "Dậu", "Sửu", "Tị", "Dậu", "Sửu"] },
  { id: 18, ten: "Đại hao (Tử khí)", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão", "Thìn", "Tị"] },
  { id: 19, ten: "Hoang vu", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị,Dậu,Sửu", "Tị,Dậu,Sửu", "Tị,Dậu,Sửu", "Thân,Tý,Thìn", "Thân,Tý,Thìn", "Thân,Tý,Thìn", "Hợi,Mão,Mùi", "Hợi,Mão,Mùi", "Hợi,Mão,Mùi", "Dần,Ngọ,Tuất", "Dần,Ngọ,Tuất", "Dần,Ngọ,Tuất"] },
  { id: 20, ten: "Băng tiêu ngọa hãm", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị", "Tý", "Sửu", "Dần", "Mão", "Tuất", "Hợi", "Ngọ", "Mùi", "Thân", "Dậu", "Thìn"] },
  { id: 21, ten: "Sát chủ", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị", "Tý", "Mùi", "Mão", "Thân", "Tuất", "Sửu", "Hợi", "Ngọ", "Dậu", "Dần", "Thìn"] },
  { id: 22, ten: "Nguyệt hình", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Tị", "Tý", "Thìn", "Thân", "Ngọ", "Sửu", "Dần", "Dậu", "Mùi", "Hợi", "Mão", "Tuất"] },
  { id: 23, ten: "Tội chỉ", yNghia: "Xấu mọi việc", loai: "mapping_thang", map: ["Ngọ", "Tý", "Mùi", "Sửu", "Thân", "Dần", "Dậu", "Mão", "Tuất", "Thìn", "Hợi", "Tị"] },
  { id: 24, ten: "Nguyệt phá", yNghia: "Xấu về xây dựng nhà", loai: "mapping_thang", map: ["Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão", "Thìn", "Tị", "Ngọ", "Mùi"] },
  { id: 25, ten: "Lôi công", yNghia: "Xấu về xây dựng nhà", loai: "mapping_thang", map: ["Dần", "Hợi", "Tị", "Thân", "Dần", "Hợi", "Tị", "Thân", "Dần", "Hợi", "Tị", "Thân"] },
  { id: 26, ten: "Phi ma sát", yNghia: "Kỵ giá thú, nhập trạch", loai: "mapping_thang", map: ["Tý", "Dậu", "Ngọ", "Mão", "Tý", "Dậu", "Ngọ", "Mão", "Tý", "Dậu", "Ngọ", "Mão"] },
  { id: 27, ten: "Chu tước hắc đạo", yNghia: "Kỵ nhập trạch, khai trương", loai: "mapping_thang", map: ["Mão", "Tị", "Mùi", "Dậu", "Hợi", "Sửu", "Mão", "Tị", "Mùi", "Dậu", "Hợi", "Sửu"] },
  { id: 28, ten: "Lỗ ban sát", yNghia: "Kỵ khởi tạo", loai: "mapping_thang", map: ["Tý", "Tý", "Tý", "Mão", "Mão", "Mão", "Ngọ", "Ngọ", "Ngọ", "Dậu", "Dậu", "Dậu"] },
  { id: 29, ten: "Phủ đầu sát", yNghia: "Kỵ khởi tạo", loai: "mapping_thang", map: ["Thìn", "Thìn", "Thìn", "Mùi", "Mùi", "Mùi", "Dậu", "Dậu", "Dậu", "Tý", "Tý", "Tý"] },
  { id: 30, ten: "Tam tang", yNghia: "Kỵ khởi tạo, giá thú, an táng", loai: "mapping_thang", map: ["Thìn", "Thìn", "Thìn", "Mùi", "Mùi", "Mùi", "Tuất", "Tuất", "Tuất", "Sửu", "Sửu", "Sửu"] },
  { id: 31, ten: "Ngũ hư", yNghia: "Kỵ khởi tạo, giá thú, an táng", loai: "mapping_thang", map: ["Tị", "Dậu", "Sửu", "Thân", "Tý", "Thìn", "Hợi", "Mão", "Mùi", "Dần", "Ngọ", "Tuất"] },
  { id: 32, ten: "Thiên tặc", yNghia: "Xấu khởi tạo, động thổ, nhập trạch, khai trương", loai: "mapping_thang", map: ["Thìn", "Dậu", "Dần", "Mùi", "Tý", "Tị", "Tuất", "Mão", "Thân", "Sửu", "Ngọ", "Hợi"] },
  { id: 33, ten: "Địa tặc", yNghia: "Xấu khởi tạo, an táng, động thổ, xuất hành", loai: "mapping_thang", map: ["Sửu", "Tý", "Hợi", "Tuất", "Dậu", "Thân", "Mùi", "Ngọ", "Tị", "Thìn", "Mão", "Dần"] },
  { id: 34, ten: "Hỏa tai", yNghia: "Xấu làm nhà, lợp nhà", loai: "mapping_thang", map: ["Sửu", "Mùi", "Dần", "Thân", "Mão", "Dậu", "Thìn", "Tuất", "Tị", "Hợi", "Ngọ", "Tý"] },
  { id: 35, ten: "Lục bất thành", yNghia: "Xấu xây dựng", loai: "mapping_thang", map: ["Dần", "Ngọ", "Tuất", "Tị", "Dậu", "Sửu", "Thân", "Tý", "Thìn", "Hợi", "Mão", "Mùi"] },
  { id: 36, ten: "Nguyệt hỏa độc hỏa", yNghia: "Xấu lợp nhà, làm bếp", loai: "mapping_thang", map: ["Tị", "Thìn", "Mão", "Dần", "Sửu", "Tý", "Hợi", "Tuất", "Dậu", "Thân", "Mùi", "Ngọ"] },
  { id: 37, ten: "Tiểu hao", yNghia: "Xấu kinh doanh, cầu tài", loai: "mapping_thang", map: ["Tị", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão", "Thìn"] },
  { id: 38, ten: "Nguyệt yếm đại họa", yNghia: "Xấu xuất hành, giá thú", loai: "mapping_thang", map: ["Tuất", "Dậu", "Thân", "Mùi", "Ngọ", "Tị", "Thìn", "Mão", "Dần", "Sửu", "Tý", "Hợi"] },
  { id: 39, ten: "Nguyệt hư (Nguyệt sát)", yNghia: "Xấu giá thú, mở cửa hàng", loai: "mapping_thang", map: ["Sửu", "Tuất", "Mùi", "Thìn", "Sửu", "Tuất", "Mùi", "Thìn", "Sửu", "Tuất", "Mùi", "Thìn"] },
  { id: 40, ten: "Hoàng sa", yNghia: "Xấu xuất hành", loai: "mapping_thang", map: ["Ngọ", "Dần", "Tý", "Ngọ", "Dần", "Tý", "Ngọ", "Dần", "Tý", "Ngọ", "Dần", "Tý"] },
  { id: 41, ten: "Nhân cách", yNghia: "Xấu giá thú, khởi tạo", loai: "mapping_thang", map: ["Dậu", "Mùi", "Tị", "Mão", "Sửu", "Hợi", "Dậu", "Mùi", "Tị", "Mão", "Sửu", "Hợi"] },
  { id: 42, ten: "Thần cách", yNghia: "Kỵ tế tự", loai: "mapping_thang", map: ["Tị", "Mão", "Sửu", "Hợi", "Dậu", "Mùi", "Tị", "Mão", "Sửu", "Hợi", "Dậu", "Mùi"] },
  { id: 43, ten: "Ngũ quỷ", yNghia: "Kỵ xuất hành", loai: "mapping_thang", map: ["Ngọ", "Dần", "Thìn", "Dậu", "Mão", "Thân", "Sửu", "Tị", "Tý", "Hợi", "Mùi", "Tuất"] },
  { id: 44, ten: "Cửu không", yNghia: "Kỵ xuất hành, cầu tài, khai trương", loai: "mapping_thang", map: ["Thìn", "Sửu", "Tuất", "Mùi", "Mão", "Tý", "Dậu", "Ngọ", "Dần", "Hợi", "Thân", "Tị"] },
  { id: 45, ten: "Trùng phục", yNghia: "Kỵ giá thú, an táng", loai: "mapping_thang", map: ["Canh", "Tân", "Kỷ", "Nhâm", "Quý", "Mậu", "Giáp", "Ất", "Kỷ", "Nhâm", "Quý", "Mậu"] },
  { id: 46, ten: "Bạch hổ", yNghia: "Kỵ mai táng (Trùng ngày Thiên giải)", loai: "mapping_thang", map: ["Ngọ", "Thân", "Tuất", "Tý", "Dần", "Thìn", "Ngọ", "Thân", "Tuất", "Tý", "Dần", "Thìn"] },
  { id: 47, ten: "Huyền vũ", yNghia: "Kỵ mai táng", loai: "mapping_thang", map: ["Dậu", "Hợi", "Sửu", "Mão", "Tị", "Mùi", "Dậu", "Hợi", "Sửu", "Mão", "Tị", "Mùi"] },
  { id: 48, ten: "Câu trận", yNghia: "Kỵ mai táng", loai: "mapping_thang", map: ["Hợi", "Sửu", "Mão", "Tị", "Mùi", "Dậu", "Hợi", "Sửu", "Mão", "Tị", "Mùi", "Dậu"] },
  { id: 49, ten: "Cô thần", yNghia: "Xấu với giá thú", loai: "mapping_thang", map: ["Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão", "Thìn", "Tị", "Ngọ", "Mùi", "Thân", "Dậu"] },
  { id: 50, ten: "Quả tú", yNghia: "Xấu với giá thú", loai: "mapping_thang", map: ["Thìn", "Tị", "Ngọ", "Mùi", "Thân", "Dậu", "Tuất", "Hợi", "Tý", "Sửu", "Dần", "Mão"] },
  { id: 51, ten: "Tứ thời đại mộ", yNghia: "Kỵ an táng", loai: "mapping_thang", map: ["Ất Mùi", "Ất Mùi", "Ất Mùi", "Bính Tuất", "Bính Tuất", "Bính Tuất", "Tân Sửu", "Tân Sửu", "Tân Sửu", "Nhâm Thìn", "Nhâm Thìn", "Nhâm Thìn"] },
  { id: 52, ten: "Ly sàng", yNghia: "Kỵ giá thú", loai: "mapping_thang", map: ["Dậu", "Dậu", "Dậu", "Dần,Ngọ", "Dần,Ngọ", "Dần,Ngọ", "Tuất", "Tuất", "Tuất", "Tị", "Tị", "Tị"] },
  { id: 53, ten: "Tứ thời cô quả", yNghia: "Kỵ giá thú", loai: "mapping_thang", map: ["Sửu", "Sửu", "Sửu", "Thìn", "Thìn", "Thìn", "Mùi", "Mùi", "Mùi", "Tuất", "Tuất", "Tuất"] },
  { id: 54, ten: "Không phòng", yNghia: "Kỵ giá thú", loai: "mapping_thang", map: ["Thìn", "Tị", "Tý", "Tuất", "Hợi", "Mùi", "Dần", "Mão", "Ngọ", "Thân", "Dậu", "Sửu"] },
  { id: 55, ten: "Âm thác", yNghia: "Kỵ xuất hành, giá thú, an táng", loai: "mapping_thang", map: ["Canh Tuất", "Tân Dậu", "Canh Thân", "Đinh Mùi", "Bính Ngọ", "Đinh Tị", "Giáp Thìn", "Ất Mão", "Giáp Dần", "Quý Sửu", "Nhâm Tý", "Quý Hợi"] },
  { id: 56, ten: "Dương thác", yNghia: "Kỵ xuất hành, giá thú, an táng", loai: "mapping_thang", map: ["Giáp Dần", "Ất Mão", "Giáp Thìn", "Đinh Tị", "Bính Ngọ", "Đinh Mùi", "Canh Thân", "Tân Dậu", "Canh Tuất", "Quý Hợi", "Nhâm Tý", "Quý Sửu"] },
  { id: 57, ten: "Quỷ khốc", yNghia: "Xấu tế tự, mai táng", loai: "mapping_thang", map: ["Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất", "Tuất"] },
  { id: 58, ten: "Xích khẩu", yNghia: "Kỵ giá thú, giao dịch, yến tiệc", loai: "ngay_theo_thang", map: [ [3, 9, 15, 21, 27], [2, 8, 14, 20, 26], [1, 7, 13, 19, 25], [6, 12, 18, 24, 30], [5, 11, 17, 23, 29], [4, 10, 16, 22, 28], [3, 9, 15, 21, 27], [2, 8, 14, 20, 26], [1, 7, 13, 19, 25], [6, 12, 14, 24, 30], [5, 11, 17, 23, 29], [4, 10, 16, 22, 28] ] },
  { id: 59, ten: "Đại không vong", yNghia: "Kỵ xuất hành, giao dịch, giao tài vật", loai: "ngay_theo_thang", map: [ [6, 14, 22, 30], [5, 13, 21, 29], [4, 12, 20, 28], [3, 11, 19, 27], [2, 10, 18, 26], [1, 17, 24], [8, 16, 24], [7, 15, 23], [6, 14, 22, 30], [5, 13, 21, 29], [4, 12, 20, 28], [3, 11, 19, 27] ] },
  { id: 60, ten: "Tiểu không vong", yNghia: "Kỵ xuất hành, giao dịch, giao tài vật", loai: "ngay_theo_thang", map: [ [2, 10, 18, 26], [1, 9, 17, 25], [8, 16, 24], [7, 15, 23], [6, 14, 22, 30], [5, 13, 21, 29], [4, 12, 20, 28], [3, 11, 19, 27], [2, 10, 18, 26], [1, 9, 17, 25], [8, 16, 24], [7, 15, 23] ] },
  { id: 61, ten: "Dương công kỵ", yNghia: "Xấu mọi việc", loai: "ngay_theo_thang", map: [ [13], [11], [9], [7], [5], [3], [2, 29], [27], [25], [23], [21], [19] ] },
  { id: 62, ten: "Cửu thổ quỷ", yNghia: "Xấu động thổ, khởi tạo, xuất hành, giao dịch, thượng quan", loai: "co_dinh", ngay: ["Ất Dậu", "Quý Tị", "Giáp Ngọ", "Tân Sửu", "Nhâm Dần", "Kỷ Dậu", "Canh Tuất", "Đinh Sửu", "Mậu Ngọ"] },
  { id: 63, ten: "Ly sào", yNghia: "Xấu nhập trạch, giá thú", loai: "co_dinh", ngay: ["Mậu Tý", "Mậu Dần", "Mậu Thìn", "Mậu Ngọ", "Mậu Thân", "Mậu Tuất", "Kỷ Sửu", "Kỷ Tị", "Kỷ Dậu", "Tân Sửu", "Tân Mão", "Tân Tị", "Nhâm Tuất", "Quý Tị"] },
  { id: 64, ten: "Hỏa tinh", yNghia: "Xấu lợp nhà, làm bếp", loai: "nhom_thang", duLieu: { nhom_1_4_7_10: ["Ất Sửu", "Giáp Tuất", "Quý Mùi", "Nhâm Thìn", "Tân Sửu", "Canh Tuất", "Kỷ Mùi"], nhom_2_5_8_11: ["Giáp Tý", "Quý Dậu", "Nhâm Ngọ", "Tân Mão", "Canh Tý", "Kỷ Dậu", "Mậu Ngọ"], nhom_3_6_9_12: ["Nhâm Thân", "Tân Tị", "Canh Dần", "Kỷ Hợi", "Mậu Thân", "Quý Hợi"] }}
];