const QUY_NHAN_DATA = { "Giáp": { "Vũ thủy": { "Mão": "Dương QN", "Dậu": "Âm QN" },
 "Thu phân": { "Dần": "Âm QN", "Thân": "Dương QN" },
 "Sương giáng": { "Sửu": "Âm QN", "Mùi": "Dương QN" },
 "Tiểu tuyết": { "Tý": "Âm QN", "Ngọ": "Dương QN" },
 "Đông chí": { "Tỵ": "Dương QN", "Hợi": "Âm QN" },
 "Đại hàn": { "Thìn": "Dương QN", "Tuất": "Âm QN" } },
 "Ất": { "Vũ thủy": { "Tuất": "Âm QN" },
 "Xuân phân": { "Dậu": "Âm QN" },
 "Hạ chí": { "Tuất": "Âm QN" },
 "Đại Thử": { "Dậu": "Âm QN" },
 "Xử thử": { "Thân": "Dương QN"},
 "Thu phân": { "Mùi": "Dương QN"},
 "Sương giáng": { "Ngọ": "Dương QN", "Dần": "Âm QN" },
 "Tiểu tuyết": { "Tỵ": "Dương QN", "Sửu": "Âm QN" },
 "Đông chí": { "Thìn": "Dương QN", "Tý": "Âm QN" },
 "Đại hàn": { "Mão": "Dương QN", "Hợi": "Âm QN" } },
 "Bính": { "Vũ thủy": { "Hợi": "Âm QN" },
 "Xuân phân": { "Tuất": "Âm QN" },
 "Tiểu mãn": { "Hợi": "Âm QN" },
 "Hạ chí": { "Dậu": "Âm QN" },
 "Đại Thử": { "Thân": "Dương QN" },
 "Xử thử": { "Mùi": "Dương QN" },
 "Thu phân": { "Ngọ": "Dương QN" },
 "Sương giáng": { "Tỵ": "Dương QN" },
 "Tiểu tuyết": { "Thìn": "Dương QN", "Dần": "Âm QN" },
 "Đông chí": { "Sửu": "Âm QN" },
 "Đại hàn": { "Tý": "Âm QN" } },
 "Đinh": { "Vũ thủy": { "Sửu": "Âm QN" },
 "Cốc vũ": { "Hợi": "Âm QN" },
 "Tiểu mãn": { "Thân": "Dương QN" },
 "Hạ chí": { "Mùi": "Dương QN" },
 "Đại Thử": { "Ngọ": "Dương QN" },
 "Xử thử": { "Tỵ": "Dương QN" },
 "Thu phân": { "Thìn": "Dương QN" },
 "Sương giáng": { "Mão": "Dương QN" },
 "Đông chí": { "Mão": "Dương QN" },
 "Đại hàn": { "Dần": "Âm QN" } },
 "Mậu": { "Vũ thủy": { "Mão": "Dương QN", "Dậu": "Âm QN" },
 "Xuân phân": { "Thân": "Dương QN", "Dần": "Âm QN" },
 "Cốc vũ": { "Sửu": "Âm QN", "Mùi": "Dương QN" },
 "Tiểu mãn": { "Tý": "Âm QN", "Ngọ": "Dương QN" },
 "Hạ chí": { "Tỵ": "Dương QN", "Hợi": "Âm QN" },
 "Đại Thử": { "Thìn": "Dương QN", "Tuất": "Âm QN" },
 "Xử thử": { "Mão": "Dương QN", "Dậu": "Âm QN" } },
 "Kỷ": { "Vũ thủy": { "Dần": "Âm QN" },
 "Xuân phân": { "Sửu": "Âm QN" },
 "Cốc vũ": { "Tý": "Âm QN", "Thân": "Dương QN" },
 "Tiểu mãn": { "Hợi": "Âm QN", "Mùi": "Dương QN" },
 "Hạ chí": { "Tuất": "Âm QN", "Ngọ": "Dương QN" },
 "Đại Thử": { "Tỵ": "Dương QN" },
 "Xử thử": { "Ngọ": "Dương QN" },
 "Thu phân": { "Mão": "Dương QN" } },
 "Canh": { "Vũ thủy": { "Mão": "Dương QN", "Dậu": "Âm QN" },
 "Xuân phân": { "Thân": "Dương QN", "Dần": "Âm QN" },
 "Cốc vũ": { "Sửu": "Âm QN", "Mùi": "Dương QN" },
 "Tiểu mãn": { "Tý": "Âm QN", "Ngọ": "Dương QN" },
 "Hạ chí": { "Tỵ": "Dương QN", "Hợi": "Âm QN" },
 "Đại Thử": { "Thìn": "Dương QN", "Tuất": "Âm QN" },
 "Xử thử": { "Mão": "Dương QN", "Dậu": "Âm QN" } },
 "Tân": { "Vũ thủy": { "Thân": "Dương QN" },
 "Xuân phân": {"Mùi": "Dương QN" },
 "Cốc vũ": { "Dần": "Âm QN", "Ngọ": "Dương QN" },
 "Tiểu mãn": { "Sửu": "Âm QN", "Tỵ": "Dương QN" },
 "Hạ chí": { "Tý": "Âm QN", "Thìn": "Dương QN" },
 "Đại Thử": { "Mão": "Dương QN", "Hợi": "Âm QN" },
 "Xử thử": { "Tuất": "Âm QN" },
 "Thu phân": { "Dậu": "Âm QN" } },
 "Nhâm": { "Vũ thủy": { "Mùi": "Dương QN" },
 "Xuân phân": { "Ngọ": "Dương QN" },
 "Cốc vũ": { "Tỵ": "Dương QN" },
 "Tiểu mãn": { "Thìn": "Dương QN", "Dần": "Âm QN" },
 "Hạ chí": { "Mão": "Dương QN", "Sửu": "Âm QN" },
 "Đại Thử": { "Tý": "Âm QN" },
 "Xử thử": { "Hợi": "Âm QN" },
 "Thu phân": { "Tuất": "Âm QN" },
 "Sương giáng": { "Dậu": "Âm QN" },
 "Đại hàn": { "Thân": "Dương QN" } },
 "Quý": { "Vũ thủy": { "Tị": "Dương QN" },
 "Xuân phân": { "Thìn": "Dương QN" },
 "Cốc vũ": { "Mão": "Dương QN" },
 "Tiểu mãn": { "Dần": "Âm QN" },
 "Đại Thử": { "Dần": "Âm QN" },
 "Xử thử": { "Sửu": "Âm QN" },
 "Thu phân": { "Tý": "Âm QN" },
 "Sương giáng": { "Hợi": "Âm QN" },
 "Tiểu tuyết": { "Thân": "Dương QN", "Tuất": "Âm QN" },
 "Đông chí": { "Mùi": "Dương QN", "Dậu": "Âm QN" },
 "Đại hàn": { "Ngọ": "Dương QN" } } };
